# Generated by Django 3.2.11 on 2022-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_alter_games_gamename'),
        ('EBank', '0002_player_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('playerName', 'game')},
        ),
    ]
