# Generated by Django 3.2.11 on 2022-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBank', '0002_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='getOutOFJail',
            field=models.PositiveIntegerField(),
        ),
    ]
