# Generated by Django 3.2.11 on 2022-01-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBank', '0003_alter_player_getoutofjail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='getOutOFJail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
