# Generated by Django 3.2.11 on 2022-01-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_alter_games_created_at'),
        ('EBank', '0004_auto_20220115_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.games'),
        ),
    ]
