# Generated by Django 3.2.11 on 2022-01-09 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 9, 15, 19, 10, 956689))),
            ],
        ),
    ]
