# Generated by Django 3.2.11 on 2022-01-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 15, 25, 50, 563283)),
        ),
    ]
