# Generated by Django 3.2.11 on 2022-01-11 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_games_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 24, 23, 855673)),
        ),
    ]
