# Generated by Django 3.2.11 on 2022-01-16 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_remove_games_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
